### ISSUE TITLE
How to install this 

### ISSUE THREAD

**Issue by tansolar** [zeyanthecoder/Teron-AI#1]
Hi im bit new to programming if you could give me a bit of more information about installing would be nice thanks :)

**Comment by zeyanthecoder** [comment]
Hey!
Sorry for late response and thank for trying out the program!

To install the program and run it on your device
1. just download or clone the repo 
2. Unzip the .zip file
3. download all the modules using pip command 
4. Check out readme for more information

If you use it please star the repo!

**Comment by ghost** [comment]
Hey!
Sorry for late response and thank for trying out the program!

To install the program and run it on your device

just download or clone the repo
Unzip the .zip file
download all the modules using pip command
Check out readme for more information
If you use it please star the repo!
